# Generated by Django 3.2.18 on 2023-04-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
